{
 "title": "ChatRoom DevOps Dashboard",
 "tags": [
  "devops",
  "chat"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Traffic (Req/Sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "App Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Messages Posted (Rate)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/messages\", method=\"POST\"}[5m]))",
     "legendFormat": "Messages/sec"
    }
   ]
  },
  {
   "title": "App CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}